import { config } from 'dotenv';
import path from 'path';

// jest automatically sets NODE_ENV as test
config({
  path: path.join(__dirname, `../../.env.${process.env.NODE_ENV ?? 'dev'}`)
});

const {
  PORT,
  NODE_ENV,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  SERVICE_NAME,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  JWKS_URI,
  PRIVATE_KEY,
  WHITELIST_ORIGIN,
  ADMIN_DEFAULT_FIRSTNAME,
  ADMIN_DEFAULT_LASTNAME,
  ADMIN_DEFAULT_EMAIL,
  ADMIN_DEFAULT_PASSWORD
} = process.env;

export const Config = {
  PORT,
  NODE_ENV,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  SERVICE_NAME,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  JWKS_URI,
  PRIVATE_KEY,
  WHITELIST_ORIGIN,
  ADMIN_DEFAULT_FIRSTNAME,
  ADMIN_DEFAULT_LASTNAME,
  ADMIN_DEFAULT_EMAIL,
  ADMIN_DEFAULT_PASSWORD
};
